// default package
// Generated 8 ene. 2021 9:15:50 by Hibernate Tools 5.4.21.Final

package Hibernate;
import java.util.Date;

/**
 * CalidadAire generated by hbm2java
 */
public class CalidadAire  implements java.io.Serializable {


     private Date fechaHora;
     private Municipio municipio;
     private Integer no2;
     private String no2Txt;
     private Integer pm10;
     private String pm10Txt;
     private Integer so2;
     private String so2Txt;
     private Double media;

    public CalidadAire() {
    }

	
    public CalidadAire(Date fechaHora, Municipio municipio) {
        this.fechaHora = fechaHora;
        this.municipio = municipio;
    }
    public CalidadAire(Date fechaHora, Municipio municipio, Integer no2, String no2Txt, Integer pm10, String pm10Txt, Integer so2, String so2Txt, Double media) {
       this.fechaHora = fechaHora;
       this.municipio = municipio;
       this.no2 = no2;
       this.no2Txt = no2Txt;
       this.pm10 = pm10;
       this.pm10Txt = pm10Txt;
       this.so2 = so2;
       this.so2Txt = so2Txt;
       this.media = media;
    }
   
    public Date getFechaHora() {
        return this.fechaHora;
    }
    
    public void setFechaHora(Date fechaHora) {
        this.fechaHora = fechaHora;
    }
    public Municipio getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(Municipio municipio) {
        this.municipio = municipio;
    }
    public Integer getNo2() {
        return this.no2;
    }
    
    public void setNo2(Integer no2) {
        this.no2 = no2;
    }
    public String getNo2Txt() {
        return this.no2Txt;
    }
    
    public void setNo2Txt(String no2Txt) {
        this.no2Txt = no2Txt;
    }
    public Integer getPm10() {
        return this.pm10;
    }
    
    public void setPm10(Integer pm10) {
        this.pm10 = pm10;
    }
    public String getPm10Txt() {
        return this.pm10Txt;
    }
    
    public void setPm10Txt(String pm10Txt) {
        this.pm10Txt = pm10Txt;
    }
    public Integer getSo2() {
        return this.so2;
    }
    
    public void setSo2(Integer so2) {
        this.so2 = so2;
    }
    public String getSo2Txt() {
        return this.so2Txt;
    }
    
    public void setSo2Txt(String so2Txt) {
        this.so2Txt = so2Txt;
    }
    public Double getMedia() {
        return this.media;
    }
    
    public void setMedia(Double media) {
        this.media = media;
    }




}


