package Hibernate;
// Generated 1 feb. 2021 9:01:43 by Hibernate Tools 5.4.21.Final

/**
 * CalidadAire generated by hbm2java
 */
public class CalidadAire implements java.io.Serializable {

	private CalidadAireId id;
	private Estaciones estaciones;
	private String calidad;
	private Double pm25;
	private Double pm10;
	private Double so2;
	private Double no2;
	private Double o3;
	private Double co;

	public CalidadAire() {
	}

	public CalidadAire(CalidadAireId id, Estaciones estaciones) {
		this.id = id;
		this.estaciones = estaciones;
	}

	public CalidadAire(CalidadAireId id, Estaciones estaciones, String calidad, Double pm25, Double pm10, Double so2,
			Double no2, Double o3, Double co) {
		this.id = id;
		this.estaciones = estaciones;
		this.calidad = calidad;
		this.pm25 = pm25;
		this.pm10 = pm10;
		this.so2 = so2;
		this.no2 = no2;
		this.o3 = o3;
		this.co = co;
	}

	public CalidadAireId getId() {
		return this.id;
	}

	public void setId(CalidadAireId id) {
		this.id = id;
	}

	public Estaciones getEstaciones() {
		return this.estaciones;
	}

	public void setEstaciones(Estaciones estaciones) {
		this.estaciones = estaciones;
	}

	public String getCalidad() {
		return this.calidad;
	}

	public void setCalidad(String calidad) {
		this.calidad = calidad;
	}

	public Double getPm25() {
		return this.pm25;
	}

	public void setPm25(Double pm25) {
		this.pm25 = pm25;
	}

	public Double getPm10() {
		return this.pm10;
	}

	public void setPm10(Double pm10) {
		this.pm10 = pm10;
	}

	public Double getSo2() {
		return this.so2;
	}

	public void setSo2(Double so2) {
		this.so2 = so2;
	}

	public Double getNo2() {
		return this.no2;
	}

	public void setNo2(Double no2) {
		this.no2 = no2;
	}

	public Double getO3() {
		return this.o3;
	}

	public void setO3(Double o3) {
		this.o3 = o3;
	}

	public Double getCo() {
		return this.co;
	}

	public void setCo(Double co) {
		this.co = co;
	}

}
