package Hibernate;
// default package
// Generated 8 ene. 2021 9:15:50 by Hibernate Tools 5.4.21.Final


import java.util.HashSet;
import java.util.Set;

/**
 * EspaciosNaturales generated by hbm2java
 */
public class EspaciosNaturales  implements java.io.Serializable {


     private int codEnaturales;
     private Municipio municipio;
     private String nombre;
     private String descripcion;
     private String tipo;
     private Long latitud;
     private Long longitud;
     private String foto;
     private Set muniEspacioses = new HashSet(0);
     private Set favEspacioses = new HashSet(0);

    public EspaciosNaturales() {
    }

	
    public EspaciosNaturales(int codEnaturales, Municipio municipio) {
        this.codEnaturales = codEnaturales;
        this.municipio = municipio;
    }
    public EspaciosNaturales(int codEnaturales, Municipio municipio, String nombre, String descripcion, String tipo, Long latitud, Long longitud, String foto, Set muniEspacioses, Set favEspacioses) {
       this.codEnaturales = codEnaturales;
       this.municipio = municipio;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.tipo = tipo;
       this.latitud = latitud;
       this.longitud = longitud;
       this.foto = foto;
       this.muniEspacioses = muniEspacioses;
       this.favEspacioses = favEspacioses;
    }
   
    public int getCodEnaturales() {
        return this.codEnaturales;
    }
    
    public void setCodEnaturales(int codEnaturales) {
        this.codEnaturales = codEnaturales;
    }
    public Municipio getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(Municipio municipio) {
        this.municipio = municipio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Long getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(Long latitud) {
        this.latitud = latitud;
    }
    public Long getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(Long longitud) {
        this.longitud = longitud;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public Set getMuniEspacioses() {
        return this.muniEspacioses;
    }
    
    public void setMuniEspacioses(Set muniEspacioses) {
        this.muniEspacioses = muniEspacioses;
    }
    public Set getFavEspacioses() {
        return this.favEspacioses;
    }
    
    public void setFavEspacioses(Set favEspacioses) {
        this.favEspacioses = favEspacioses;
    }




}


