package Hibernate;
// default package
// Generated 8 ene. 2021 9:15:50 by Hibernate Tools 5.4.21.Final



/**
 * Estaciones generated by hbm2java
 */
public class Estaciones  implements java.io.Serializable {


     private int codEstacion;
     private Municipio municipio;
     private String nombre;
     private String direccion;
     private Long coordX;
     private Long coordY;
     private Long latitud;
     private Long longitud;
     private String foto;

    public Estaciones() {
    }

	
    public Estaciones(int codEstacion, Municipio municipio) {
        this.codEstacion = codEstacion;
        this.municipio = municipio;
    }
    public Estaciones(int codEstacion, Municipio municipio, String nombre, String direccion, Long coordX, Long coordY, Long latitud, Long longitud, String foto) {
       this.codEstacion = codEstacion;
       this.municipio = municipio;
       this.nombre = nombre;
       this.direccion = direccion;
       this.coordX = coordX;
       this.coordY = coordY;
       this.latitud = latitud;
       this.longitud = longitud;
       this.foto = foto;
    }
   
    public int getCodEstacion() {
        return this.codEstacion;
    }
    
    public void setCodEstacion(int codEstacion) {
        this.codEstacion = codEstacion;
    }
    public Municipio getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(Municipio municipio) {
        this.municipio = municipio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Long getCoordX() {
        return this.coordX;
    }
    
    public void setCoordX(Long coordX) {
        this.coordX = coordX;
    }
    public Long getCoordY() {
        return this.coordY;
    }
    
    public void setCoordY(Long coordY) {
        this.coordY = coordY;
    }
    public Long getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(Long latitud) {
        this.latitud = latitud;
    }
    public Long getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(Long longitud) {
        this.longitud = longitud;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }




}


