package Hibernate;
// default package
// Generated 8 ene. 2021 9:15:50 by Hibernate Tools 5.4.21.Final



/**
 * FavEspaciosId generated by hbm2java
 */
public class FavEspaciosId  implements java.io.Serializable {


     private int codEnaturales;
     private int codUsuario;

    public FavEspaciosId() {
    }

    public FavEspaciosId(int codEnaturales, int codUsuario) {
       this.codEnaturales = codEnaturales;
       this.codUsuario = codUsuario;
    }
   
    public int getCodEnaturales() {
        return this.codEnaturales;
    }
    
    public void setCodEnaturales(int codEnaturales) {
        this.codEnaturales = codEnaturales;
    }
    public int getCodUsuario() {
        return this.codUsuario;
    }
    
    public void setCodUsuario(int codUsuario) {
        this.codUsuario = codUsuario;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FavEspaciosId) ) return false;
		 FavEspaciosId castOther = ( FavEspaciosId ) other; 
         
		 return (this.getCodEnaturales()==castOther.getCodEnaturales())
 && (this.getCodUsuario()==castOther.getCodUsuario());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodEnaturales();
         result = 37 * result + this.getCodUsuario();
         return result;
   }   


}


