package Hibernate;
// default package
// Generated 8 ene. 2021 9:15:50 by Hibernate Tools 5.4.21.Final



/**
 * FavEspacios generated by hbm2java
 */
public class FavEspacios  implements java.io.Serializable {


     private FavEspaciosId id;
     private EspaciosNaturales espaciosNaturales;
     private Usuario usuario;

    public FavEspacios() {
    }

    public FavEspacios(FavEspaciosId id, EspaciosNaturales espaciosNaturales, Usuario usuario) {
       this.id = id;
       this.espaciosNaturales = espaciosNaturales;
       this.usuario = usuario;
    }
   
    public FavEspaciosId getId() {
        return this.id;
    }
    
    public void setId(FavEspaciosId id) {
        this.id = id;
    }
    public EspaciosNaturales getEspaciosNaturales() {
        return this.espaciosNaturales;
    }
    
    public void setEspaciosNaturales(EspaciosNaturales espaciosNaturales) {
        this.espaciosNaturales = espaciosNaturales;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


