package Hibernate;
// default package
// Generated 8 ene. 2021 9:15:50 by Hibernate Tools 5.4.21.Final



/**
 * FavMunicipioId generated by hbm2java
 */
public class FavMunicipioId  implements java.io.Serializable {


     private int codMuni;
     private int codUsuario;

    public FavMunicipioId() {
    }

    public FavMunicipioId(int codMuni, int codUsuario) {
       this.codMuni = codMuni;
       this.codUsuario = codUsuario;
    }
   
    public int getCodMuni() {
        return this.codMuni;
    }
    
    public void setCodMuni(int codMuni) {
        this.codMuni = codMuni;
    }
    public int getCodUsuario() {
        return this.codUsuario;
    }
    
    public void setCodUsuario(int codUsuario) {
        this.codUsuario = codUsuario;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FavMunicipioId) ) return false;
		 FavMunicipioId castOther = ( FavMunicipioId ) other; 
         
		 return (this.getCodMuni()==castOther.getCodMuni())
 && (this.getCodUsuario()==castOther.getCodUsuario());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodMuni();
         result = 37 * result + this.getCodUsuario();
         return result;
   }   


}


