package Hibernate;
// default package
// Generated 8 ene. 2021 9:15:50 by Hibernate Tools 5.4.21.Final



/**
 * FavMunicipio generated by hbm2java
 */
public class FavMunicipio  implements java.io.Serializable {


     private FavMunicipioId id;
     private Municipio municipio;
     private Usuario usuario;

    public FavMunicipio() {
    }

    public FavMunicipio(FavMunicipioId id, Municipio municipio, Usuario usuario) {
       this.id = id;
       this.municipio = municipio;
       this.usuario = usuario;
    }
   
    public FavMunicipioId getId() {
        return this.id;
    }
    
    public void setId(FavMunicipioId id) {
        this.id = id;
    }
    public Municipio getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(Municipio municipio) {
        this.municipio = municipio;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


