package Hibernate;
// Generated 29 ene. 2021 12:58:21 by Hibernate Tools 5.4.21.Final

/**
 * Hash generated by hbm2java
 */
public class Hash implements java.io.Serializable {

	private String nombre;
	private String hash;

	public Hash() {
	}

	public Hash(String nombre) {
		this.nombre = nombre;
	}

	public Hash(String nombre, String hash) {
		this.nombre = nombre;
		this.hash = hash;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getHash() {
		return this.hash;
	}

	public void setHash(String hash) {
		this.hash = hash;
	}

}
