package Hibernate;
// default package
// Generated 8 ene. 2021 9:15:50 by Hibernate Tools 5.4.21.Final



/**
 * Hash generated by hbm2java
 */
public class Hash  implements java.io.Serializable {


     private int codHash;
     private String nombre;
     private String hash;

    public Hash() {
    }

	
    public Hash(int codHash, String hash) {
        this.codHash = codHash;
        this.hash = hash;
    }
    public Hash(int codHash, String nombre, String hash) {
       this.codHash = codHash;
       this.nombre = nombre;
       this.hash = hash;
    }
   
    public int getCodHash() {
        return this.codHash;
    }
    
    public void setCodHash(int codHash) {
        this.codHash = codHash;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getHash() {
        return this.hash;
    }
    
    public void setHash(String hash) {
        this.hash = hash;
    }




}


