package Hibernate;
// default package
// Generated 8 ene. 2021 9:15:50 by Hibernate Tools 5.4.21.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Municipio generated by hbm2java
 */
public class Municipio  implements java.io.Serializable {


     private int codMuni;
     private Provincia provincia;
     private String nombre;
     private String descripcion;
     private Set favMunicipios = new HashSet(0);
     private Set estacioneses = new HashSet(0);
     private Set calidadAires = new HashSet(0);
     private Set muniEspacioses = new HashSet(0);
     private Set espaciosNaturaleses = new HashSet(0);

    public Municipio() {
    }

	
    public Municipio(int codMuni, Provincia provincia) {
        this.codMuni = codMuni;
        this.provincia = provincia;
    }
    public Municipio(int codMuni, Provincia provincia, String nombre, String descripcion, Set favMunicipios, Set estacioneses, Set calidadAires, Set muniEspacioses, Set espaciosNaturaleses) {
       this.codMuni = codMuni;
       this.provincia = provincia;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.favMunicipios = favMunicipios;
       this.estacioneses = estacioneses;
       this.calidadAires = calidadAires;
       this.muniEspacioses = muniEspacioses;
       this.espaciosNaturaleses = espaciosNaturaleses;
    }
   
    public int getCodMuni() {
        return this.codMuni;
    }
    
    public void setCodMuni(int codMuni) {
        this.codMuni = codMuni;
    }
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getFavMunicipios() {
        return this.favMunicipios;
    }
    
    public void setFavMunicipios(Set favMunicipios) {
        this.favMunicipios = favMunicipios;
    }
    public Set getEstacioneses() {
        return this.estacioneses;
    }
    
    public void setEstacioneses(Set estacioneses) {
        this.estacioneses = estacioneses;
    }
    public Set getCalidadAires() {
        return this.calidadAires;
    }
    
    public void setCalidadAires(Set calidadAires) {
        this.calidadAires = calidadAires;
    }
    public Set getMuniEspacioses() {
        return this.muniEspacioses;
    }
    
    public void setMuniEspacioses(Set muniEspacioses) {
        this.muniEspacioses = muniEspacioses;
    }
    public Set getEspaciosNaturaleses() {
        return this.espaciosNaturaleses;
    }
    
    public void setEspaciosNaturaleses(Set espaciosNaturaleses) {
        this.espaciosNaturaleses = espaciosNaturaleses;
    }




}


