package Hibernate;
// default package
// Generated 8 ene. 2021 9:15:50 by Hibernate Tools 5.4.21.Final



/**
 * MuniEspaciosId generated by hbm2java
 */
public class MuniEspaciosId  implements java.io.Serializable {


     private int codMuni;
     private int codEnaturales;

    public MuniEspaciosId() {
    }

    public MuniEspaciosId(int codMuni, int codEnaturales) {
       this.codMuni = codMuni;
       this.codEnaturales = codEnaturales;
    }
   
    public int getCodMuni() {
        return this.codMuni;
    }
    
    public void setCodMuni(int codMuni) {
        this.codMuni = codMuni;
    }
    public int getCodEnaturales() {
        return this.codEnaturales;
    }
    
    public void setCodEnaturales(int codEnaturales) {
        this.codEnaturales = codEnaturales;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MuniEspaciosId) ) return false;
		 MuniEspaciosId castOther = ( MuniEspaciosId ) other; 
         
		 return (this.getCodMuni()==castOther.getCodMuni())
 && (this.getCodEnaturales()==castOther.getCodEnaturales());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodMuni();
         result = 37 * result + this.getCodEnaturales();
         return result;
   }   


}


