package Hibernate;
// default package
// Generated 8 ene. 2021 9:15:50 by Hibernate Tools 5.4.21.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Provincia generated by hbm2java
 */
public class Provincia  implements java.io.Serializable {


     private int codProv;
     private String nombre;
     private Set municipios = new HashSet(0);

    public Provincia() {
    }

	
    public Provincia(int codProv) {
        this.codProv = codProv;
    }
    public Provincia(int codProv, String nombre, Set municipios) {
       this.codProv = codProv;
       this.nombre = nombre;
       this.municipios = municipios;
    }
   
    public int getCodProv() {
        return this.codProv;
    }
    
    public void setCodProv(int codProv) {
        this.codProv = codProv;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getMunicipios() {
        return this.municipios;
    }
    
    public void setMunicipios(Set municipios) {
        this.municipios = municipios;
    }




}


