package Hibernate;
// default package
// Generated 8 ene. 2021 9:15:50 by Hibernate Tools 5.4.21.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer codUsuario;
     private String nombre;
     private String contraseña;
     private String PClave;
     private Set favMunicipios = new HashSet(0);
     private Set favEspacioses = new HashSet(0);

    public Usuario() {
    }

    public Usuario(String nombre, String contraseña, String PClave, Set favMunicipios, Set favEspacioses) {
       this.nombre = nombre;
       this.contraseña = contraseña;
       this.PClave = PClave;
       this.favMunicipios = favMunicipios;
       this.favEspacioses = favEspacioses;
    }
   
    public Integer getCodUsuario() {
        return this.codUsuario;
    }
    
    public void setCodUsuario(Integer codUsuario) {
        this.codUsuario = codUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getContraseña() {
        return this.contraseña;
    }
    
    public void setContraseña(String contraseña) {
        this.contraseña = contraseña;
    }
    public String getPClave() {
        return this.PClave;
    }
    
    public void setPClave(String PClave) {
        this.PClave = PClave;
    }
    public Set getFavMunicipios() {
        return this.favMunicipios;
    }
    
    public void setFavMunicipios(Set favMunicipios) {
        this.favMunicipios = favMunicipios;
    }
    public Set getFavEspacioses() {
        return this.favEspacioses;
    }
    
    public void setFavEspacioses(Set favEspacioses) {
        this.favEspacioses = favEspacioses;
    }




}


