// default package
// Generated 19 ene. 2021 8:41:31 by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

/**
 * EspaciosNaturales generated by hbm2java
 */
public class EspaciosNaturales implements java.io.Serializable {

	private int codEnatural;
	private String nombre;
	private String descripcion;
	private String tipo;
	private Double latitud;
	private Double longitud;
	private String foto;
	private Set muniEspacioses = new HashSet(0);

	public EspaciosNaturales() {
	}

	public EspaciosNaturales(int codEnatural) {
		this.codEnatural = codEnatural;
	}

	public EspaciosNaturales(int codEnatural, String nombre, String descripcion, String tipo, Double latitud,
			Double longitud, String foto, Set muniEspacioses) {
		this.codEnatural = codEnatural;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.tipo = tipo;
		this.latitud = latitud;
		this.longitud = longitud;
		this.foto = foto;
		this.muniEspacioses = muniEspacioses;
	}

	public int getCodEnatural() {
		return this.codEnatural;
	}

	public void setCodEnatural(int codEnatural) {
		this.codEnatural = codEnatural;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Double getLatitud() {
		return this.latitud;
	}

	public void setLatitud(Double latitud) {
		this.latitud = latitud;
	}

	public Double getLongitud() {
		return this.longitud;
	}

	public void setLongitud(Double longitud) {
		this.longitud = longitud;
	}

	public String getFoto() {
		return this.foto;
	}

	public void setFoto(String foto) {
		this.foto = foto;
	}

	public Set getMuniEspacioses() {
		return this.muniEspacioses;
	}

	public void setMuniEspacioses(Set muniEspacioses) {
		this.muniEspacioses = muniEspacioses;
	}

}
