// default package
// Generated 19 ene. 2021 8:41:31 by Hibernate Tools 5.4.21.Final

/**
 * Hash generated by hbm2java
 */
public class Hash implements java.io.Serializable {

	private int codHash;
	private String nombre;
	private String hash;
	private String url;

	public Hash() {
	}

	public Hash(int codHash) {
		this.codHash = codHash;
	}

	public Hash(int codHash, String nombre, String hash, String url) {
		this.codHash = codHash;
		this.nombre = nombre;
		this.hash = hash;
		this.url = url;
	}

	public int getCodHash() {
		return this.codHash;
	}

	public void setCodHash(int codHash) {
		this.codHash = codHash;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getHash() {
		return this.hash;
	}

	public void setHash(String hash) {
		this.hash = hash;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

}
